### ISSUE TITLE
ERR failed to execute run command error="unable to determine which docker image to run: unexpected status '401' from test-composer: Unauthorized\n"

### ISSUE THREAD

**Issue by anh65498** [saucelabs/saucectl-cypress-example#13]
I am working at SAP and I am trying to execute the `$ saucectl run` command in my local repo. I `$ git clone` this remote repo, installed Docker and let it run, set my Sauce Labs Credentials in CLI and `credential.yml`, `$ npm install cypress` in saucectl-cypress-example folder, installed saucectl globally,  connected to SAP VPN via BIG-IP Edge Client, but the `$saucectl run` command failed with this error 

<img width="750" alt="Screen Shot 2021-07-06 at 10 24 48 AM" src="https://user-images.githubusercontent.com/15056430/124656716-67811a80-de56-11eb-9602-a4409b972386.png">

What could be the issue and the fix here?

**Comment by alexplischke** [comment]
Hm. I know it's a bit of a mundane request, but could you verify the username & access key for any typos (I'd assume you already did it, but just in case 😅 )?

**Comment by anh65498** [comment]
Thank you for the reply Alex. I got 1 extra letter at the beginning of my Access Key that I didn't notice earlier. Your answer solved my error.
