### ISSUE TITLE
Best practice for including dependencies in cypress tests? 

### ISSUE THREAD

**Issue by dwjohnston** [saucelabs/saucectl-cypress-example#23]
It's common to import external dependencies into your cypress tests - eg [adding cypress testing library](https://testing-library.com/docs/cypress-testing-library/intro). 

Your example doesn't demonstrate what the best way to do this is. 

I've created a couple of repros to demonstrate the issues I have: 

https://github.com/dwjohnston/saucectl-cypress-example/tree/run-local-v1

This one here works fine, and just shows that you can run cypress directly on your machine, as well as with saucectl. 

https://github.com/dwjohnston/saucectl-cypress-example/tree/run-local-b

This one attempts to add cypress testing library. It works fine running cypress directly but starts failing in sourcectl. 

Initially it fails becauce `@testing-library/cypress` can't be found. I remove `node_modules` from the `.sauceignore` but then it fails on weird windows errors. 

Is there a well tested best practice for this kind of thing?

**Comment by alexplischke** [comment]
There are two ways in which you can add dependencies.

1. Specify them via the `config.yml`.
2. Include `node_modules` as part of the archive (which is what you did 💪 ).

Both approaches are **equally** viable and we don't recommend one over the other.

Having said that, we are currently investigating an issue where certain dependencies may fail to be recognized if a pre-processor is involved in the process (say, typescript or cucumber).

Please feel free to leave a link to one of your Sauce Labs jobs, so we can have a better look!
