### ISSUE TITLE
Value not accepted for mac according to IDE

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/saucectl-cypress-example#32]
Getting `Value not accepted` in the [current config](https://github.com/saucelabs/saucectl-cypress-example/blob/751881d451eb95a1480b028165e9b8c8a46882a7/.sauce/config.yml#L52)

<img width="1088" alt="Screen Shot 2022-03-11 at 10 41 46 AM" src="https://user-images.githubusercontent.com/2136245/157899662-9c4c6901-fb57-4cc6-85e5-c84760776e81.png">

**Comment by alexplischke** [comment]
Addressed via https://github.com/saucelabs/saucectl-cypress-example/commit/aa5f23e87805a2ef1f857c0a17e8acb4a318fe40 👍
