### ISSUE TITLE
Running specific tests using cucumber tag not working when using saucectl

### ISSUE THREAD

**Issue by zberhe** [saucelabs/saucectl-cypress-example#35]
I am using cypress-cucumber-processor and trying to run tagged scenarios. I am passing the tag to cypress using `CYPRESS_TAGS="@smoke"` when running saucectl i.e `saucectl run -e CYPRESS_TAGS="@smoke"`. But it is running all tests instead of the tagged one.  Is there another way to pass this parameter to cypress when using saucectl?

**Comment by alexplischke** [comment]
Are you using https://www.npmjs.com/package/cypress-tags ? If so, it sounds like it should be `CYPRESS_INCLUDE_TAGS` instead. Do you have an example job we can take a closer look at?

**Comment by mhan83** [comment]
@zberhe were you able to try the suggestion to run your tests like this: `saucectl run -e CYPRESS_TAGS=@smoke`? In my testing with or without quotes works so there may be different behaviour depending on your shell?

If you're still having trouble, please include repro steps and we can try to assist.

**Comment by zberhe** [comment]
Thank you @ma-santamaria for your suggestion. That solved my issue: `saucectl run -e CYPRESS_TAGS=@smoke`
